[platformio]
default_envs = node_a_esp32

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
  arduino-libraries/Ethernet@^2.0.2
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^4.0.5
  bblanchon/ArduinoJson@^7.1.0
build_flags =
  -DSERVER_IP_1=192
  -DSERVER_IP_2=168
  -DSERVER_IP_3=1
  -DSERVER_IP_4=10
  -DSERVER_PORT=5000
  -DNETWORK_SUBNET_1=255
  -DNETWORK_SUBNET_2=255
  -DNETWORK_SUBNET_3=255
  -DNETWORK_SUBNET_4=0
  -DNETWORK_GATEWAY_1=192
  -DNETWORK_GATEWAY_2=168
  -DNETWORK_GATEWAY_3=1
  -DNETWORK_GATEWAY_4=1
  -DNETWORK_DNS_1=8
  -DNETWORK_DNS_2=8
  -DNETWORK_DNS_3=8
  -DNETWORK_DNS_4=8
  -DMAC_1=0xDE
  -DMAC_2=0xAD
  -DMAC_3=0xBE
  -DMAC_4=0xEF
  -DMAC_5=0xFE
  -DCYCLE_INTERVAL_MS=1000
  -DNETWORK_TIMEOUT_MS=1300
  -DREMOTE_CMD_TTL_MS=5000
  -DSIMULATED_COOLING=1
  -DANOMALY_TEMP_C=80
  -DCRITICAL_TEMP_C=88
  -DHEAT_GAIN_C_PER_SEC=2.8
  -DHOT_TO_LIQUID_COEFF=0.22
  -DHOT_TO_AMBIENT_COEFF=0.03
  -DLIQUID_TO_AMBIENT_COEFF=0.11
  -DFLOW_COOLING_COEFF=0.24
  -DDEFAULT_AMBIENT_C=26
  -DINITIAL_HOT_C=40
  -DINITIAL_LIQUID_C=34

[env:node_a_esp32]
platform = espressif32@6.9.0
board = esp32dev
build_flags =
  ${env.build_flags}
  -DNODE_ID=\"A\"
  -DDEVICE_NAME=\"NODE_A_ESP32\"
  -DMAC_6=0xA1
  -DDEVICE_IP_4=100
  -DW5500_CS_PIN=5
  -DW5500_RESET_PIN=4
  -DW5500_SCK_PIN=18
  -DW5500_MISO_PIN=19
  -DW5500_MOSI_PIN=23
  -DONE_WIRE_PIN=14
  -DFAN_PIN=17
  -DPUMP_PIN=16

[env:node_b_pico]
platform = raspberrypi
board = pico
build_flags =
  ${env.build_flags}
  -DNODE_ID=\"B\"
  -DDEVICE_NAME=\"NODE_B_RP2040\"
  -DMAC_6=0xB2
  -DDEVICE_IP_4=101
  -DW5500_CS_PIN=17
  -DW5500_RESET_PIN=20
  -DW5500_SCK_PIN=18
  -DW5500_MISO_PIN=16
  -DW5500_MOSI_PIN=19
  -DONE_WIRE_PIN=2
  -DFAN_PIN=11
  -DPUMP_PIN=10
