[platformio]
default_envs = rack_r00, rack_r07

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.1.0
  links2004/WebSockets@^2.6.1
build_flags =
  -DWIFI_SSID=\"CHANGE_ME_SSID\"
  -DWIFI_PASSWORD=\"CHANGE_ME_PASS\"
  -DSERVER_HOST=\"192.168.1.10\"
  -DEDGE_WS_PORT=8765
  -DEDGE_WS_PATH=\"/\"
  -DCYCLE_INTERVAL_MS=1000
  -DNETWORK_TIMEOUT_MS=1500
  -DREMOTE_CMD_TTL_MS=5000
  -DSIMULATED_COOLING=0
  -DANOMALY_TEMP_C=80
  -DCRITICAL_TEMP_C=88
  -DHEAT_WINDOW_MS=2000
  -DHEAT_GAIN_C_PER_SEC=2.8
  -DHOT_TO_LIQUID_COEFF=0.22
  -DHOT_TO_AMBIENT_COEFF=0.03
  -DLIQUID_TO_AMBIENT_COEFF=0.11
  -DDEFAULT_AMBIENT_C=26
  -DINITIAL_HOT_C=40
  -DINITIAL_LIQUID_C=34

[env:rack_r00]
; Primary rack profile
platform = espressif8266
board = esp12e
lib_deps =
  ${env.lib_deps}
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^4.0.5
build_flags =
  ${env.build_flags}
  -DDEVICE_ROLE=1
  -DNODE_ID=\"RACK_A\"
  -DRACK_ID=\"R00\"
  -DDEVICE_NAME=\"RACK_R00_ESP8266\"
  -DONE_WIRE_PIN=4
  -DHEAT_PIN=5
  -DHEATER_RATED_POWER_W=1.44

[env:rack_r07]
; Paired rack profile
platform = espressif8266
board = esp12e
lib_deps =
  ${env.lib_deps}
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^4.0.5
build_flags =
  ${env.build_flags}
  -DDEVICE_ROLE=1
  -DNODE_ID=\"RACK_B\"
  -DRACK_ID=\"R07\"
  -DDEVICE_NAME=\"RACK_R07_ESP8266\"
  -DONE_WIRE_PIN=4
  -DHEAT_PIN=5
  -DHEATER_RATED_POWER_W=1.44

[env:cdu_esp32c6]
; CDU deployment profile: 2 racks, 2 fans, 2 Peltiers
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.37
board = esp32-c6-devkitc-1
lib_ignore =
  control
  sensors
platform_packages =
  framework-arduinoespressif32@https://github.com/espressif/arduino-esp32/releases/download/3.3.7/esp32-core-3.3.7.tar.xz
  framework-arduinoespressif32-libs@https://github.com/espressif/arduino-esp32/releases/download/3.3.7/esp32-core-3.3.7-libs.tar.xz
build_flags =
  ${env.build_flags}
  -DDEVICE_ROLE=2
  -DDEVICE_NAME=\"CDU_ESP32C6\"
  -DCDU_ID=\"CDU1\"
  -DCDU_FAN_A_PIN=6
  -DCDU_FAN_B_PIN=7
  -DCDU_PELTIER_A_PIN=18
  -DCDU_PELTIER_B_PIN=19
  -DCDU_PELTIER_ACTIVE_HIGH=1
